### ISSUE TITLE
OpenVR2Key Installation trouble

### ISSUE THREAD

**Issue by Inktrinket** [BOLL7708/OpenVR2Key#1]
Hi! I have been trying to install this application but due to some weirdness, things are not operating properly. For example, the file named OpenVR2Key is a "Microsoft Visual Studio Solution" file for me??? (I am not sure but I don't think it is supposed to be that type of file.) And whenever I open Steam VR and try to locate the app through the controller settings it is undetected - The instructions seemed vague on how to install the application properly. Any help is appreciated, thank you!

**Comment by Inktrinket** [comment]
Oh, nevermind - I'm actually just stupid lol

**Comment by BOLL7708** [comment]
I guess you downloaded the source instead of the executable 😅 

I still get some oddities with the binding interface not showing up anymore after running multiple background applications with input support. Been poking Valve about it, but no response so far 🤷‍♂️ Will try to figure out what is going on there as it's interrupting my own tools from working properly if run simultaneously.

So yeah, uh... there are some issues still. 😬

**Comment by Inktrinket** [comment]
Yeah, when I was having the issue I contacted my friend and he told me that
I downloaded the wrong files. The user interface makes it a little
confusing in all honestly but after realizing what the platform is used for
its more understandable.

Sorry for the confusion as well as the late response, have a good day.
