### ISSUE TITLE
WASD movement?

### ISSUE THREAD

**Issue by Spinfusor99** [BOLL7708/OpenVR2Key#12]
Is there a way to map typical FPS shooter movement keys (WASD) to either Index thumbsticks?

**Comment by BOLL7708** [comment]
Hah, I see you added this before writing in the SteamVR forums. And yes it is possible. 

To simulate the WSAD keys, it's already prepared in the default Index bindings. If you show the window for this application you'll see that it shows various values for the cardinal directions of your sticks in the `Active keys` section up top, doing it diagonally shows two values as the trigger areas intersect. I think you can affect how this works in the bindings directly, but it's been a while since I set that up so not entirely sure.

In any case, you bind this to get it to work, for the respective hand:
* L9, R9 = W
* L10, R10 = D
* L11, R11 = S
* L12, R12 = A

**Comment by Spinfusor99** [comment]
Worked great!  Thank you.

One feature request - could you add the ability to assign multiple keys to one button?  i.e. L9 = W & {arrow up}?
