### ISSUE TITLE
No OPENVR2KEY in drop down

### ISSUE THREAD

**Issue by FluffyDiscord** [BOLL7708/OpenVR2Key#5]
Here locate OPENVR2KEY in the drop down, then switch the Active Controller Binding to CUSTOM and click EDIT THIS BINDING. This will open the Controller Binding interface.

I have no such app there. I have the exe added as non steam game, enabled in overlay (addon), but I still can't find it.

![image](https://user-images.githubusercontent.com/10332247/92501971-821b4080-f1ff-11ea-832a-8470e0e12c7c.png)

**Comment by BOLL7708** [comment]
Yeah, this is an issue that has existed since the new dashboard was launched, if I remember it correctly. If you turn on advanced settings in the bottom left corner of the SteamVR settings and then access the old bindings interface it will most likely exist in that list, near the bottom, with a black icon.

I reported this once two years ago, but closed it as I also had problems with my application manifests, but it has started happening now again so I guess I should open a new issue with Valve 😔

**Comment by FluffyDiscord** [comment]
Yep, found it there, as you said. Now it's working, thank you _it's amazing_

Side question - there is a game (Unity engine, I suspect using OpenVR) which is using the binding.json file for knuckles, but the controllers are not reaction to anything else in game, except for tracking. Do you think the author didn't map it properly (at all) or there could be something else ?

**Comment by BOLL7708** [comment]
Sounds like bindings aren't loaded at all. Poses can still be read outside the input system, both are still valid, but for buttons the new input system is kind of what we have to use. I would check in the console if it reports failure to load the bindings, then report it to the developer of the game:
```SteamVR status window > 🍔 > Developer > Web Console```
