### ISSUE TITLE
im trying to get it to where when i press a key it plays a sound on soundpad

### ISSUE THREAD

**Issue by da123487** [BOLL7708/OpenVR2Key#61]

**Comment by BOLL7708** [comment]
Seems a lot of people do this, there is some tutorial video I've heard, do you have a link to that so I can see their explanation?

**Comment by da123487** [comment]
yes i think so

**Comment by da123487** [comment]
but theres 2 tutorials ive seen

**Comment by da123487** [comment]
ill show you the best one in my opinion

**Comment by da123487** [comment]
https://www.youtube.com/watch?v=f9ZOBYzTpUQ

**Comment by BOLL7708** [comment]
That sure is a good tutorial, and does say basically everything I would. I don't know what headset you are using, but I expect it to be a Quest or other non-steamVR native headset. My main headset is the Index so I usually have a hard time replicating these issues, well, it just works over here, thus problem. 🤔 

A lot of people seem to have issues, but also a lot of people appear to have it working just fine, I'm quite curious to know what the difference is in the process between those two groups, maybe it's a step when installing it, where it is on the drive, or if there is antivirus software.

Yeah, because I don't know what information I need to try and fix any of this, I get to ask... everything, and I'm not sure if either of us is up for that 🤣

**Comment by da123487** [comment]
I use a quest headset but I followed another comments instruction and those instructions said that he was correct so I did those steps but it did not work. but I use WinRAR it has an antivirus system but I don't know if that has to do with anything.

**Comment by BOLL7708** [comment]
I think there can be issues if you unpacked it into Program Files, so if you did try to run it from a folder outside of that instead. Otherwise, I'd probably have to see some screenshots or something to know what is going on.

**Comment by BOLL7708** [comment]
Closed due to no reply.
