### ISSUE TITLE
"unblocked" when i try to see what keys im pressing

### ISSUE THREAD

**Issue by mrbeast20** [BOLL7708/OpenVR2Key#74]
### Current behavior

i try to bind my keys it says unblocked. i try to look at what youve said to other people and i cant understand it  please help.

### Steps to reproduce the behavior

set keys too? i dont understand this section

### Expected behavior

active keys: none

### Operating system version

windows11

### SteamVR version

1.26.7

### Application version

0.57

### VR HMD

quest 2

### VR hardware

quest 2 controllers

### Software to control

soundpad

### Game

gorilla tag

### Additional information

N/A

**Comment by BOLL7708** [comment]
Are you running Gorilla Tag natively on the Quest 2 or in SteamVR? Due to the volume of issues from users with this exact scenario there has to be a common issue that people bump into, most issues end with "fixed it" though. Unblocked just means that it should be listening to input, compared to being blocked which it is if the SteamVR dashboard is visible.

**Comment by BOLL7708** [comment]
Closed due to no reply.
